[package]
name = "chip_eight_emulator"
version = "0.1.0"
authors = ["Ed <ed.pizzella@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
rand = "0.7.3"
sdl2 = "0.34.3"